### PR TITLE
Updated for Ubuntu 22.04 LTS and DRM 3.4.4

### PR DESCRIPTION
**Pull request by DavideBonfanti**

### CODE REVIEW

**Comment by Gallium70** [comment]
It may be better adding a `--user-agent="Mozilla/5.0"` option to `wget`, otherwise the download request may be rejected by Dell's server.

**Comment by DavideBonfanti** [comment]
> It may be better adding a `--user-agent="Mozilla/5.0"` option to `wget`, otherwise the download request may be rejected by Dell's server.

I've tried with `drm` as user agent and it works on Dell server, maybe it has filter against `wget` or `curl` :wink:

**Comment by kscherer** [comment]
Thank you for the PR. I have integrated your changes locally and tried to upgrade a 3.4.2 instance to 3.4.4, but something went wrong (database locked?) and now the service is broken. Please give me some time to debug and verify the patches.

**Comment by Gallium70** [comment]
> > It may be better adding a `--user-agent="Mozilla/5.0"` option to `wget`, otherwise the download request may be rejected by Dell's server.
> 
> I've tried with `drm` as user agent and it works on Dell server, maybe it has filter against `wget` or `curl` 😉

Oh, I didn't realize that `-U` is short for `--user-agent` for `wget` .🥲 Never mind.


> Thank you for the PR. I have integrated your changes locally and tried to upgrade a 3.4.2 instance to 3.4.4, but something went wrong (database locked?) and now the service is broken. Please give me some time to debug and verify the patches.

I noticed this problem as well, that if I attach the data volume create by 3.4.2 directly to a fresh new 3.4.4 container, the database seems broken. I assume there might be some format or schema change. Upgrade from 3.4.4 to 3.4.5 seems OK, though.

I read through release notes and user guides of DRM, however I didn't find any specific instructions or steps for a update. I didn't investigate it further, since it's my first time deploying DRM so I just deleted the data volume and recreated it with a 3.4.4 container. Now I can think of three possible workarouds that might be able to preserve data (not tested):

- Upgrade DRM inside the old 3.4.2 container (e.g. copy the new installer in and execute it), kill & remove it, and replace with new 3.4.4 container; this should be the closest to an upgrade operation process when DRM is installed on a seperate machine;
- Upgrade through every minor version (e.g. 3.4.2 -> 3.4.3 -> 3.4.4 -> 3.4.5);
- Mount data volume when building new docker image ([RUN --mount=type=cache](https://docs.docker.com/reference/dockerfile/#run---mounttypecache) ?), hoping the installer might upgrade existing database during installation process; this is suspect and it contradicts cache mount's intended usecase.

**Comment by kscherer** [comment]
Many thanks for the PR. I merged the 2 PRs into a single commit.

**Pull request closed without merging**
